#!/bin/bash

# stare: a simplified wrapper on entr.
# Copyright (C) 2023 jahinzee
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public
# License along with this program. If not, see
# <https://www.gnu.org/licenses/>.

command -v entr &> /dev/null || {
  echo -e >&2 "stare: 'entr' could not be found. See:\n  * https://eradman.com/entrproject/\n  * https://repology.org/project/entr/versions";
  exit 1;
}

test "$#" -ge 2 || {
  echo -e >&2 "stare: Usage: stare <file> <command> [<args> ...]"
  exit 1;
}

FILENAME="$1";
shift;
COMMAND="$@";

test -f "$FILENAME" || {
  echo -e >&2 "stare: no such file: $FILENAME";
  exit 1
}

command -v "$COMMAND" || {
  echo -e >&2 "stare: no such command: $FILENAME";
}

FILE="$(/usr/bin/ls -1 $FILENAME &> /dev/null)"
echo "$FILE" | entr -ccsrn "$COMMAND";
